name: Sync master to preview
on:
  push:
    branches:
      - 'master'
jobs:
  sync-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge master -> preview
        uses: devmasx/merge-branch@v1.3.0
        with:
          type: now
          from_branch: master
          target_branch: preview
          github_token: ${{ secrets.GITHUB_TOKEN }}
