name: Reject pull requests on preview branch

on:
  pull_request:
    types: [opened, reopened]
    branches:
      - preview

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: codelytv/no-pull-requests@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          message: The preview branch does not accept pull requests.  You probably want to use master.
