name: Reject pull requests on preview branch

on:
  pull_request_target:
    types: [opened, reopened]
    branches:
      - preview

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: SiliconLabs/close-pull-request-target
      with:
        # Optional. Post a issue comment just before closing a pull request.
        comment: "Preview branch does not accept pull requests.  You probably want to use master."
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
