name: Reject pull requests on preview branch

on:
  pull_request_target:
    types: [opened, reopened]
    branches: 
      - preview

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: SiliconLabs/close-pull-request-target@v2.2
      with:
        comment: "The preview branch does not accept pull requests.  To contribute to BSSw.io make your PR against the master branch.  Thanks"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
