name: Recreate preview brand from scratch
on:
  workflow_dispatch
  
jobs:
  find-open-pull-requests:
    runs-on: ubuntu-latest
    steps:
      - name: List open pull requests
        uses: k-kinzal/pr-action/show@master
        with:
          args: -l "state == `\"open\"`"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  recreate-preview-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Delete old preview branch
        uses: dawidd6/action-delete-branch@v3
        with:
          branches: preview
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create new preview branch
        uses: peterjgrainger/action-create-branch@v1.0.0
        with:
          branch: 'preview'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  merge-pull-requests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        head_shas: ["e5fb16319aa0a639fd925c90a2242dff106772fb", "61d1bf23aba73b2d1dbdec58ca89c50f065c5e20"]
    steps:
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"
      - uses: devmasx/merge-branch@v1.3.0
        with:
          type: now
          head_to_merge: ${{ matrix.head_shas }}
          target_branch: preview
          github_token: ${{ secrets.GITHUB_TOKEN }}
