name: Recreate preview brand from scratch
on:
  workflow_dispatch
  
jobs:
  recreate-preview-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Delete old preview branch
        uses: dawidd6/action-delete-branch@v3
        with:
          branches: preview
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create new preview branch
        uses: peterjgrainger/action-create-branch@v1.0.0
        with:
          branch: 'preview'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: List open pull requests
        uses: k-kinzal/pr-action/validate@master
        with:
          args: -l "state == `\"open\"`" -l "{url: url}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
      - name: output
        run: echo '${{ steps.list.outputs.pulls }}'
#      - name: Trigger open PRs to synchronize
#        uses: yellowmegaman/prtrigger@v0.8
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
